### PR TITLE
feat: Chatbot streaming

### PR DESCRIPTION
**Pull request by nicele08**
```shell
curl -X 'POST' \
  'http://127.0.0.1:8000/api/chatbot' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuaXlpbmRhZ2lyaXllQGdtYWlsLmNvbSIsImV4cCI6MTY5ODY1OTA5OX0.e0Ayiy0DIuS7AXypAyULdMXpUvl-LAOVJX9d88VKlEk' \
  -H 'Content-Type: application/json' \
  -d '{
  "kinyarwanda_question": "Nizihe ndwara ziterwa n'\'' imirire mibi?"
}'
```

### CODE REVIEW

**Comment by rutsam** [comment]
@nicele08 Did you include pinecone in the code?

**Comment by rutsam** [comment]
@kurt0cougar kindly review and merge the code

**Comment by nicele08** [comment]
> @nicele08 Did you include pinecone in the code?

@rutsam I didn't use pinecone. Are there features that need pinecone?

**Comment by rutsam** [comment]
No, I think i saw it in the code and wanted to know if you had used it, but I do not think we need it

**Comment by nicele08** [comment]
> to know if you had used it, but I do not think we need it

You're right. I think you mean here while I was trying streaming but I found langchain is enough so I removed the `pinecone`:
```python
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY', '')
PINECONE_ENVIRONMENT = os.getenv('PINECONE_ENVIRONMENT', '')
```

**Pull request merged**
